// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RajProj.Data;

namespace RajProj.Migrations
{
    [DbContext(typeof(RajContext))]
    [Migration("20200520141941_Merchant")]
    partial class Merchant
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RajProj.Models.Merchant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxDailyTransactionAmount")
                        .HasColumnType("int");

                    b.Property<string>("MerhchantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinDailyTranAmount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Merchant");
                });
#pragma warning restore 612, 618
        }
    }
}
